# Generated by Django 5.0.3 on 2025-04-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена покупки')),
                ('category', models.PositiveIntegerField(choices=[(0, 'Приложение'), (1, 'Минуты')], default=0, verbose_name='Категория')),
            ],
        ),
    ]
