# Generated by Django 5.0.3 on 2025-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='Название'),
        ),
    ]
