# Generated by Django 5.0.3 on 2025-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_options_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Приложение')], default=0, verbose_name='Категория'),
        ),
    ]
