# Generated by Django 5.0.3 on 2025-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Минуты в приложениях'), (1, 'Вредные привычки')], default=0, verbose_name='Категория'),
        ),
    ]
