# Generated by Django 5.0.3 on 2025-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=100, verbose_name='Задание')),
                ('description', models.CharField(default='-', max_length=200, verbose_name='Описание задания')),
                ('category', models.PositiveIntegerField(choices=[(0, 'Спорт'), (1, 'Учеба'), (2, 'Работа'), (3, 'Дом')], default=3, verbose_name='Категория')),
                ('start_date', models.TimeField(verbose_name='Время начала задания')),
                ('end_date', models.TimeField(verbose_name='Дедлайн')),
                ('price', models.PositiveIntegerField(verbose_name='Награда за выполение задания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
