# Generated by Django 5.0.3 on 2025-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Нужно сделать'), (1, 'В процессе'), (2, 'Сделано')], default=0, verbose_name='Статус задачи'),
        ),
    ]
