# Generated by Django 5.0.3 on 2025-04-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='_', max_length=100, verbose_name='Имя пользователя')),
                ('email', models.CharField(default='_', max_length=100, verbose_name='e-mail')),
                ('password', models.CharField(default='_', max_length=100, verbose_name='Пароль')),
                ('balance', models.PositiveIntegerField(verbose_name='Баланс')),
                ('sub_active', models.BooleanField(verbose_name='Подписка')),
                ('sub_due_to_date', models.DateTimeField(auto_now_add=True, verbose_name='Активна до')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
