# Generated by Django 5.0.3 on 2025-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_active',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_due_to_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активна до'),
        ),
    ]
