# Generated by Django 5.0.3 on 2025-04-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_balance_user_sub_active_user_sub_due_to_date'),
        ('group', '0002_group_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='group.group', verbose_name='Группа'),
        ),
    ]
