# Generated by Django 5.0.3 on 2025-04-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_id',
        ),
    ]
