# Generated by Django 5.0.3 on 2025-04-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
