# Generated by Django 5.0.3 on 2025-04-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_group'),
        ('group', '0008_alter_group_members_delete_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='group.group', verbose_name='Группа'),
        ),
    ]
