# Generated by Django 5.0.3 on 2025-04-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Идентификатор группы'),
        ),
    ]
