# Generated by Django 5.0.3 on 2025-04-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
    ]
