# Generated by Django 5.0.3 on 2025-04-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_membership_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
    ]
