# Generated by Django 5.0.3 on 2025-04-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена подписки')),
                ('payment_type', models.PositiveIntegerField(choices=[(0, 'Т-банк'), (1, 'Сбер'), (2, 'СБП')], default=2, verbose_name='Тип оплаты')),
                ('payment_external_id', models.PositiveIntegerField(verbose_name='ID платежа')),
                ('status', models.PositiveIntegerField(choices=[(0, '-'), (1, 'На проверке'), (2, 'Успешно'), (3, 'Ошибка')], default=0, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(verbose_name='Время заказа')),
                ('pay_at', models.DateTimeField(verbose_name='Время подтверждения оплаты')),
            ],
        ),
    ]
