# Generated by Django 5.0.3 on 2025-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время подтверждения оплаты'),
        ),
    ]
