# Generated by Django 5.0.3 on 2025-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
